### ISSUE TITLE
data: analytics, experimentation, user journeys

### ISSUE THREAD

**Issue by tomholford** [tloncorp/lure#42]
# Context

We are currently flying blind and have little insight into:

- how users are finding and interacting with Lure
- what the conversion rate and user journey is for invitee --> onboardee

# Changes

- [ ] add JS script to frontend
- [ ] POST events from backend agent to PostHog
- [ ] fire events at key stages of the user journey (e.g., user entered patp, user navigated to group)
- [ ] build funnels based on aforementioned events in PostHog for analysis and future iteration
- [ ] use A/B testing to experiment with copy, designs, etc

# TODO

- [ ] which business questions are we trying to answer? which funnels do we care about? what are the key stages of those funnels?

**Comment by lukestiles** [comment]
We are most concerned about conversion to retention funnel. For landing pages it will be further up the funnel and tracking link usage and then conversion to registered user.

The broader visibility will generate data we can begin to interrogate and use to test hypotheses without needing to update tagging.

**Comment by zalberico** [comment]
Will be tracking this outside of this repo
